# Generated by Django 5.2.8 on 2025-11-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('VULNERABLE', 'Vulnerable'), ('NOT_VULNERABLE', 'Not Vulnerable'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('report_html', models.TextField(blank=True)),
                ('report_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='reports.vulnerabilityreport')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('method_name', models.CharField(max_length=255)),
                ('exploitable', models.BooleanField(default=False)),
                ('confidence', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('explanation', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reports.vulnerabilityreport')),
            ],
            options={
                'ordering': ['-confidence', 'file_path', 'line_number'],
            },
        ),
    ]
