# Generated by Django 5.2.8 on 2025-11-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEInfo',
            fields=[
                ('cve_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('affected_packages', models.JSONField(default=list)),
                ('vulnerable_methods', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.CharField(default='OSV', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CVE Information',
                'verbose_name_plural': 'CVE Information',
                'ordering': ['-last_updated'],
            },
        ),
    ]
